// DescribeElementResponse.cs
// Copyright © 2012–Present Jackalope Technologies, Inc. and Doug Gerard.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

namespace SnoopMCP.Protocol.Tools;

/// <summary>
///     Wire response for the <c>describeElement</c> tool — a self-contained snapshot of a
///     WPF element's identity, layout, content, and binding state.
/// </summary>
/// <param name="Id">Stable element id assigned by the payload's element registry.</param>
/// <param name="Type">CLR type's short name (no namespace).</param>
/// <param name="Name">The element's <c>x:Name</c> if set; otherwise <c>null</c>.</param>
/// <param name="AutomationId">The element's <c>AutomationProperties.AutomationId</c> if set; otherwise <c>null</c>.</param>
/// <param name="Bounds">Bounds in the root visual's coordinate space; zero rect when unavailable.</param>
/// <param name="VisibleText">Concatenated visible text from this subtree, capped at 200 chars.</param>
/// <param name="IsInTemplate">True when the element was generated by a control template.</param>
/// <param name="HasBindingErrors">True when any local binding expression reports an error or error status.</param>
/// <param name="Path">Canonical visual-tree path string (Task 9 grammar).</param>
/// <param name="ChildCount">Visual child count, or 0 for non-visual elements.</param>
/// <param name="DataContextType">Full CLR type name of the element's data context, or <c>null</c>.</param>
/// <param name="HashCode">
///     Result of <see cref="System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(object)" /> for
///     cross-call equality checks.
/// </param>
/// <param name="IsAlive">True when the element is still in memory at the time of describe.</param>
public sealed record DescribeElementResponse(
    int Id,
    string Type,
    string? Name,
    string? AutomationId,
    BoundsDto Bounds,
    string VisibleText,
    bool IsInTemplate,
    bool HasBindingErrors,
    string Path,
    int ChildCount,
    string? DataContextType,
    int HashCode,
    bool IsAlive);
