// DescribeElementResponse.cs
// Copyright © 2012–Present Jackalope Technologies, Inc. and Doug Gerard.
// SPDX-License-Identifier: MIT
// Licensed under the MIT License. See LICENSE in the repository root.

namespace SnoopMCP.Protocol.Tools;

/// <summary>
/// Wire response for the <c>describeElement</c> tool — a self-contained snapshot of a
/// WPF element's identity, layout, content, and binding state.
/// </summary>
/// <param name="Id">Stable element id assigned by the payload's element registry.</param>
/// <param name="Type">CLR type's short name (no namespace).</param>
/// <param name="Name">The element's <c>x:Name</c> if set; otherwise <c>null</c>.</param>
/// <param name="AutomationId">The element's <c>AutomationProperties.AutomationId</c> if set; otherwise <c>null</c>.</param>
/// <param name="Bounds">Layout bounds (<c>RenderSize</c>) in the root visual's coordinate space; zero rect when unavailable.</param>
/// <param name="RenderBounds">
/// The area the element and its descendants actually paint, in the same coordinate space. Usually
/// equal to <paramref name="Bounds"/>, but an element that draws outside its layout box — a modal
/// overlay host, an adorner-style painter, anything with a custom <c>OnRender</c> — can have a zero
/// <paramref name="Bounds"/> while painting across the whole window. Hit testing follows painted
/// content, so this is the rectangle that explains why such an element answered a hit (issue #75).
/// </param>
/// <param name="VisibleText">Concatenated visible text from this subtree, capped at 200 chars.</param>
/// <param name="IsInTemplate">True when the element was generated by a control template.</param>
/// <param name="HasBindingErrors">True when any local binding expression reports an error or error status.</param>
/// <param name="Path">Canonical visual-tree path string (Task 9 grammar).</param>
/// <param name="ChildCount">Visual child count, or 0 for non-visual elements.</param>
/// <param name="DataContextType">Full CLR type name of the element's data context, or <c>null</c>.</param>
/// <param name="HashCode">Result of <see cref="System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(object)"/> for cross-call equality checks.</param>
/// <param name="DataContextHashCode">
/// <see cref="System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(object)"/> of the element's
/// current <c>DataContext</c> instance, or <c>null</c> when it has none. A virtualizing panel can
/// recycle the same container (same <paramref name="Id"/>, same <paramref name="HashCode"/>) for a
/// different row's data with no error and no id change — <paramref name="HashCode"/> cannot detect
/// this because it identifies the container, not its content. Re-describing a cached <paramref
/// name="Id"/> and comparing this value against the one you saw before tells you whether the id
/// still names the same logical row before you act on stale facts (issue #78).
/// </param>
/// <param name="IsAlive">True when the element is still in memory at the time of describe.</param>
public sealed record DescribeElementResponse(
    int Id,
    string Type,
    string? Name,
    string? AutomationId,
    BoundsDto Bounds,
    BoundsDto RenderBounds,
    string VisibleText,
    bool IsInTemplate,
    bool HasBindingErrors,
    string Path,
    int ChildCount,
    string? DataContextType,
    int HashCode,
    int? DataContextHashCode,
    bool IsAlive);
