// ParentNavigator.cs
// Copyright (c) 2026 Jackalope Technologies

namespace SnoopMCP.Payload.Inspection;

using System.Windows;
using System.Windows.Media;
using SnoopMCP.Protocol.Tools;

/// <summary>
/// Climbs upward from an element via the visual or logical tree, or via the templated-parent link.
/// </summary>
public sealed class ParentNavigator
{
    /// <summary>Tree kind: visual.</summary>
    public const string TreeKindVisual = "visual";

    /// <summary>Tree kind: logical.</summary>
    public const string TreeKindLogical = "logical";

    private readonly ElementDescriber mDescriber;

    /// <summary>
    /// Initialises a new <see cref="ParentNavigator"/>.
    /// </summary>
    /// <param name="describer">The describer used to snapshot the resolved parent.</param>
    public ParentNavigator(ElementDescriber describer)
    {
        ArgumentNullException.ThrowIfNull(describer);
        mDescriber = describer;
    }

    /// <summary>
    /// Returns the visual or logical parent of <paramref name="element"/> as a snapshot.
    /// </summary>
    /// <param name="element">The child element.</param>
    /// <param name="tree">Either <c>visual</c> or <c>logical</c>.</param>
    /// <returns>The parent snapshot, or a response whose <c>Parent</c> is <c>null</c> at a root.</returns>
    public GetParentResponse GetParent(DependencyObject element, string tree)
    {
        ArgumentNullException.ThrowIfNull(element);
        ArgumentException.ThrowIfNullOrEmpty(tree);

        DependencyObject? parent = tree switch
        {
            TreeKindVisual => ResolveVisualParent(element),
            TreeKindLogical => LogicalTreeHelper.GetParent(element),
            _ => throw new ArgumentException(
                $"Tree '{tree}' must be '{TreeKindVisual}' or '{TreeKindLogical}'.",
                nameof(tree))
        };

        DescribeElementResponse? described = parent is null ? null : mDescriber.Describe(parent);
        return new GetParentResponse(described);
    }

    /// <summary>
    /// Returns the templated parent of <paramref name="element"/> as a snapshot, when the element
    /// was generated by a control template.
    /// </summary>
    /// <param name="element">The element.</param>
    /// <returns>The templated parent snapshot, or a response whose <c>TemplatedParent</c> is <c>null</c>.</returns>
    public GetTemplatedParentResponse GetTemplatedParent(DependencyObject element)
    {
        ArgumentNullException.ThrowIfNull(element);

        DependencyObject? templated = element switch
        {
            FrameworkElement fe => fe.TemplatedParent,
            FrameworkContentElement fce => fce.TemplatedParent,
            _ => null
        };

        DescribeElementResponse? described = templated is null ? null : mDescriber.Describe(templated);
        return new GetTemplatedParentResponse(described);
    }

    private static DependencyObject? ResolveVisualParent(DependencyObject element)
    {
        DependencyObject? parent = null;
        bool isVisual = element is Visual or System.Windows.Media.Media3D.Visual3D;
        if (isVisual)
        {
            parent = VisualTreeHelper.GetParent(element);
        }
        return parent;
    }
}
